### PR TITLE
feat(ai-sdr): change to org pipelines and refactor get domain pipeline input

### PR DESCRIPTION
**Pull request by chuang8511**
Because

- demo used personal pipeline which could run out of credit
- The input of users data are too limit, which makes result not so accurate

This commit

- change to org pipelines
- add more inputs to increase the accuracy

p.s. The test data has been changed to the apollo files

### CODE REVIEW

**Comment by xiaofei-du** [comment]
Hi @chuang8511, since you are updating the following file name to be consistent with the other demos?   

`ai-sdr/app.py` -> `ai-sdr/streamlit_app.py`

**Review by xiaofei-du — CHANGES_REQUESTED** [review]
Hi @chuang8511, since you are updating the following file name to be consistent with the other demos?   

`ai-sdr/app.py` -> `ai-sdr/streamlit_app.py`

**Comment by chuang8511** [comment]
@xiaofei-du Please review it again. Thank you.

**Review by xiaofei-du — CHANGES_REQUESTED** [review]
Please implement the following changes:

- Update the ai-sdr README to clarify accepted CSV file formats.
- Enhance the UI by providing hints to users on the expected format for their CSV files.
- Consider providing test data to illustrate the expected inputs for users.

**Comment by chuang8511** [comment]
@xiaofei-du 
Please review it.
- Update the ai-sdr README to clarify expected inputs from the CSV file.
image

- Enhance the UI by providing hints to users on the expected inputs for their CSV files.
- Consider providing test data to illustrate the expected inputs for users.
image

**Pull request merged**
